--TABLA DE USUARIOS (Perfil Público)
CREATE TABLE IF NOT EXISTS public.usuarios (
    id_usuarios UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre_usuario TEXT,
    correo_electronico TEXT,
    contrasena TEXT, -- Hash guardado 
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Activar seguridad
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;

-- Política: Los usuarios pueden ver su propio perfil
CREATE POLICY "Usuarios ven su propio perfil" ON public.usuarios
    FOR SELECT USING (auth.uid() = id_usuarios);

-- TABLA DE CICLOS
CREATE TABLE IF NOT EXISTS public.ciclos (
    id_ciclo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio DATE NOT NULL,
    duracion_ciclo INT4 DEFAULT 28,
    duracion_sangrado INT4 DEFAULT 5,
    fk_usuario UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.ciclos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuarios ven sus propios ciclos" ON public.ciclos
    FOR SELECT USING (auth.uid() = fk_usuario);

-- 4. TABLA DE SÍNTOMAS (Catálogo)
CREATE TABLE IF NOT EXISTS public.sintomas (
    id_sintomas BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_sintoma TEXT NOT NULL,
    categoria TEXT 
);

ALTER TABLE public.sintomas ENABLE ROW LEVEL SECURITY;

-- Política: Todo el mundo puede leer los síntomas (público)
CREATE POLICY "Lectura publica sintomas" ON public.sintomas
    FOR SELECT TO anon, authenticated USING (true);

-- TABLA REGISTRO DE SÍNTOMAS (Diario)
CREATE TABLE IF NOT EXISTS public.registro_sintoma (
    id_registro_sintoma UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    fk_usuario UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    fk_sintomas BIGINT REFERENCES public.sintomas(id_sintomas),
    fk_ciclo BIGINT REFERENCES public.ciclos(id_ciclo) ON DELETE SET NULL,
    fecha DATE NOT NULL,
    intensidad INT4 DEFAULT 1,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.registro_sintoma ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Usuarios ven sus propios registros" ON public.registro_sintoma
    FOR SELECT USING (auth.uid() = fk_usuario);


-- Tarjetas Informativas
CREATE TABLE IF NOT EXISTS public.info_tarjetas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icono TEXT,
    titulo TEXT,
    descripcion TEXT,
    orden INT4 DEFAULT 1
);

ALTER TABLE public.info_tarjetas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Lectura publica tarjetas" ON public.info_tarjetas
    FOR SELECT TO anon, authenticated USING (true);

-- Acordeón Educativo
CREATE TABLE IF NOT EXISTS public.info_acordeon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT,
    contenido TEXT,
    orden INT4 DEFAULT 1
);

ALTER TABLE public.info_acordeon ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Lectura publica acordeon" ON public.info_acordeon
    FOR SELECT TO anon, authenticated USING (true);


-- DATOS INICIALES


-- Insertar Síntomas Básicos
INSERT INTO public.sintomas (nombre_sintoma, categoria) VALUES 
('Dolor de cabeza', 'Físico'),
('Cólicos', 'Físico'),
('Fatiga', 'Energía'),
('Tristeza', 'Emocional'),
('Ansiedad', 'Emocional'),
('Acné', 'Piel'),
('Hinchazón', 'Digestivo'),
('Antojo dulce', 'Apetito'),
('Mareos', 'Físico'),
('Insomnio', 'Energía')
ON CONFLICT DO NOTHING; 


